import type { LucideIcon } from "lucide-react";
import {
  Award,
  Bot,
  BookOpen,
  Building2,
  Calendar,
  Camera,
  CheckCircle2,
  Clapperboard,
  Compass,
  CreditCard,
  Dumbbell,
  Film,
  Flame,
  Gift,
  Globe,
  Headphones,
  Heart,
  Laptop,
  Layers,
  LayoutTemplate,
  Lightbulb,
  MapPin,
  Mic,
  Mic2,
  MessageCircle,
  Monitor,
  Music,
  Newspaper,
  Package,
  Palette,
  PartyPopper,
  PenTool,
  Presentation,
  Rocket,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Type,
  Users,
  Video,
  Wand2,
  Zap,
} from "lucide-react";

/**
 * Kho icon dùng cho sảnh/sản phẩm thêm mới qua Supabase — gõ đúng tên (VD: "Rocket", "Bot")
 * vào cột `icon` trên bảng catalog_products. Gõ sai tên hoặc để trống sẽ tự dùng icon mặc định.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Award,
  Bot,
  BookOpen,
  Building2,
  Calendar,
  Camera,
  CheckCircle2,
  Clapperboard,
  Compass,
  CreditCard,
  Dumbbell,
  Film,
  Flame,
  Gift,
  Globe,
  Headphones,
  Heart,
  Laptop,
  Layers,
  LayoutTemplate,
  Lightbulb,
  MapPin,
  Mic,
  Mic2,
  MessageCircle,
  Monitor,
  Music,
  Newspaper,
  Package,
  Palette,
  PartyPopper,
  PenTool,
  Presentation,
  Rocket,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Type,
  Users,
  Video,
  Wand2,
  Zap,
};

const DEFAULT_ICON = Sparkles;

export function getIconComponent(name: string | null | undefined): LucideIcon {
  if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
  return DEFAULT_ICON;
}
