/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DoiMatKhauRouteImport } from './routes/doi-mat-khau'
import { Route as HuongDanSkillRouteImport } from './routes/huong-dan-skill'
import { Route as TaiSkillRouteImport } from './routes/tai-skill'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as SkillIdRouteImport } from './routes/skill.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiMatKhauRoute = DoiMatKhauRouteImport.update({
  id: '/doi-mat-khau',
  path: '/doi-mat-khau',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanSkillRoute = HuongDanSkillRouteImport.update({
  id: '/huong-dan-skill',
  path: '/huong-dan-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiSkillRoute = TaiSkillRouteImport.update({
  id: '/tai-skill',
  path: '/tai-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIdRoute = SkillIdRouteImport.update({
  id: '/skill/$id',
  path: '/skill/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/doi-mat-khau': typeof DoiMatKhauRoute
  '/huong-dan-skill': typeof HuongDanSkillRoute
  '/tai-skill': typeof TaiSkillRoute
  '/order/$id': typeof OrderIdRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/doi-mat-khau': typeof DoiMatKhauRoute
  '/huong-dan-skill': typeof HuongDanSkillRoute
  '/tai-skill': typeof TaiSkillRoute
  '/order/$id': typeof OrderIdRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/doi-mat-khau': typeof DoiMatKhauRoute
  '/huong-dan-skill': typeof HuongDanSkillRoute
  '/tai-skill': typeof TaiSkillRoute
  '/order/$id': typeof OrderIdRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dang-ky'
    | '/dang-nhap'
    | '/doi-mat-khau'
    | '/huong-dan-skill'
    | '/tai-skill'
    | '/order/$id'
    | '/skill/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dang-ky'
    | '/dang-nhap'
    | '/doi-mat-khau'
    | '/huong-dan-skill'
    | '/tai-skill'
    | '/order/$id'
    | '/skill/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/dang-ky'
    | '/dang-nhap'
    | '/doi-mat-khau'
    | '/huong-dan-skill'
    | '/tai-skill'
    | '/order/$id'
    | '/skill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  DoiMatKhauRoute: typeof DoiMatKhauRoute
  HuongDanSkillRoute: typeof HuongDanSkillRoute
  TaiSkillRoute: typeof TaiSkillRoute
  OrderIdRoute: typeof OrderIdRoute
  SkillIdRoute: typeof SkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-mat-khau': {
      id: '/doi-mat-khau'
      path: '/doi-mat-khau'
      fullPath: '/doi-mat-khau'
      preLoaderRoute: typeof DoiMatKhauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan-skill': {
      id: '/huong-dan-skill'
      path: '/huong-dan-skill'
      fullPath: '/huong-dan-skill'
      preLoaderRoute: typeof HuongDanSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-skill': {
      id: '/tai-skill'
      path: '/tai-skill'
      fullPath: '/tai-skill'
      preLoaderRoute: typeof TaiSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$id': {
      id: '/skill/$id'
      path: '/skill/$id'
      fullPath: '/skill/$id'
      preLoaderRoute: typeof SkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  DoiMatKhauRoute: DoiMatKhauRoute,
  HuongDanSkillRoute: HuongDanSkillRoute,
  TaiSkillRoute: TaiSkillRoute,
  OrderIdRoute: OrderIdRoute,
  SkillIdRoute: SkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
